### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by owocado** [Androz2091/instaddict#2]
Hi,

So I requested my data and tried to import it which gave me this error:
![Screenshot_20210706-183408_Chrome](https://user-images.githubusercontent.com/24418520/124605361-7208d780-de89-11eb-8a14-92966eeeead1.png)

If you need anything from me, please let me know. Thanks for making another cool project. :P

**Comment by Androz2091** [comment]
Thank you for reporting this bug, the issue has been fixed! 👍
