### ISSUE TITLE
Changes to Data Package

### ISSUE THREAD

**Issue by kero3009destiny** [Androz2091/instaddict#6]
The data package had some changes since Instaddict was made.

`account_information` folder was renamed to `personal_information`

`followers.json` under `followers_and_following` was renamed to `followers_1.json` (there may be follower splitting, my account only has 1 file with 641 followers)

Below is how the followers file currently looks like
````json
[
  {
    "title": "",
    "media_list_data": [
      
    ],
    "string_list_data": [
      {
        "href": "https://www.instagram.com/username",
        "value": "username",
        "timestamp": 1676354318
      }
    ]
  }
]

**Comment by jazzathedev** [comment]
I know this is really late, but i have fixed this
